ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿ if 0
³ Normal 9-voice AdLib GLOBALS ........................ by Jens-Christian Huus ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
³ Some GLOBALS used by the ADLIB player.                                       ³
³                                                                              ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ endif


ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿ if 0
³ *** GLOBALS ***                                                              ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ endif

GLOBAL          Version1:BYTE
GLOBAL          Max:BYTE
GLOBAL          General:WORD
GLOBAL          SeqPointer:WORD
GLOBAL          Tpoin:WORD
GLOBAL          Instrument:BYTE
GLOBAL          DataInfo:BYTE
GLOBAL          Special:BYTE
GLOBAL          Timer:BYTE

GLOBAL          Player:FAR
GLOBAL          Version2:WORD
GLOBAL          Voicon:BYTE
GLOBAL          Credits:BYTE
GLOBAL          StopVoice:NEAR
GLOBAL          Sound:NEAR

GLOBAL          Tempw:WORD
GLOBAL          ESeg:WORD
GLOBAL          EOffset:WORD
GLOBAL          Levels:BYTE
GLOBAL          Note:BYTE
GLOBAL          ShNote:BYTE
GLOBAL          Speed:BYTE
GLOBAL          Spedr:BYTE
GLOBAL          TrackPointer:WORD
GLOBAL          Inst:WORD
GLOBAL          Dur:WORD
GLOBAL          Durr:WORD
GLOBAL          SeqPoi:WORD
GLOBAL          TrackPoi:WORD
GLOBAL          Freq:WORD
GLOBAL          Gate:BYTE
GLOBAL          Transp:WORD
GLOBAL          SlFreq:WORD
GLOBAL          Nog:BYTE
GLOBAL          ShSlFreq:WORD
GLOBAL          ShGate:BYTE
GLOBAL          ShFreq:WORD
GLOBAL          Level2:BYTE
GLOBAL          Level3:BYTE
GLOBAL          Carrier:BYTE
GLOBAL          Modulator:BYTE
GLOBAL          FreqTab:WORD
GLOBAL          ShVib:WORD
GLOBAL          VWidth:BYTE
GLOBAL          VWid:BYTE
GLOBAL          Vspeed:BYTE
GLOBAL          KsLevel:BYTE
GLOBAL          AdLevel:BYTE
GLOBAL          FeedCon:BYTE
GLOBAL          MvolLo:BYTE
GLOBAL          MvolHi:BYTE
GLOBAL          BreakVoicOn:BYTE
GLOBAL          FirstSeg:WORD
GLOBAL          FirstOffset:WORD
GLOBAL          SecondSeg:WORD
GLOBAL          SecondOffset:WORD
GLOBAL          TempSeg:WORD
GLOBAL          TempOffset:WORD
GLOBAL          DivLine:WORD
GLOBAL          MvolLine:BYTE
GLOBAL          FineTune:BYTE
GLOBAL          HardRst:BYTE
GLOBAL          HardTimer:BYTE
GLOBAL          HardRel:BYTE
GLOBAL          SlReal:WORD
GLOBAL          ShSlReal:WORD

GLOBAL          Spec:WORD
GLOBAL          Specr:WORD
GLOBAL          SpArp:BYTE
GLOBAL          SpModLevel:BYTE
GLOBAL          SpModAdd:BYTE
GLOBAL          SpDur:BYTE
GLOBAL          SpRaw:BYTE

